# Generated by Django 3.0.6 on 2020-05-30 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='created_at',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='posts',
            name='updated_at',
            field=models.DateField(default=''),
        ),
    ]
