# Generated by Django 3.0.6 on 2020-05-30 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_posts_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='user',
            new_name='postinguser',
        ),
    ]
