# Generated by Django 3.0.6 on 2020-05-30 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200531_0418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='postinguser',
        ),
    ]
